Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-04c5ea94e03ab0ff5
      SecurityGroupIds: 
        - !ImportValue Securitygroup
      AvailabilityZone: ap-northeast-2a
      EbsOptimized: true
      # BlockDeviceMappings:
      #   - DeviceName: /dev/sda1
      #     Ebs:
      #       VolumeSize: 30
      #       VolumeType: gp2
      SubnetId: !ImportValue PublicSubnet
      IamInstanceProfile: !ImportValue InstanceProfile
      # UserData:
      #   Fn::Base64: !Sub |
      #     #!/bin/bash
      #     sudo apt update -y
      #     sudo apt install -u python3 python3-pip python3-vevn git
      #     pip install --upgrade pip
      #     pip install yfinance
      #     pip install flask boto3 yahooquery requests
      #     pip install googletrans==4.0.0rc1
      #     pip install python-dotenv
      #     pip install pandas
      #     pip install matplotlib
      #     pip install plotly
      #     pip install requests
      #     pip install deep-translator
      #     pip install beautifulsoup4
      #     pip install sagemaker
      #     pip install python-dateutil
      Tags:
        - Key: Name
          Value: chatbot_ec2

  ElasticIP:
    Type: AWS::EC2::EIP
  
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2
      EIP: !Ref ElasticIP

Outputs:
  EIPID:
    Description: "EIP ID"
    Value: !Ref ElasticIP
    Export:
      Name: ElasticIP